receivers:
  otlp:
    protocols:
      grpc:
  zipkin:
exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  prometheus:
    endpoint: "0.0.0.0:9464"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true
  logging:
    loglevel: debug
processors:
  batch:
    send_batch_size: 1
  resource:
    attributes:
      - key: tas.org
        value: Team
        action: insert
      - key: tas.env
        value: QA
        action: insert
service:
  pipelines:
    traces:
      receivers: [ otlp,zipkin ]
      processors: [ resource,batch ]
      exporters: [ jaeger,zipkin,logging ]
    metrics:
      receivers: [ otlp ]
      processors: [ resource,batch ]
      exporters: [ prometheus,logging ]
